language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: qH8DRD1vcnMoOEHnUWje8adhFfnI0bZhdvtHZfj6nGO6MeWAVqpgSG3ljHLn1SmTAQEhnDFjMqy+yEOJCiTUdVugqnujoN/GPez1JoRcKy//hSaVLubOyINd4pEzBZRI8ULUAc796ySQCFGf01q4N9B4aR0dTIcZGl0xw6CVbUUG0qwO6+x3zmWDw+KvPBE8OGlhZhQs4BzfugHRSj2SfsgH6OaOOdfxkGI+/5in0I0IHVnTogJOqhPYQekBlnw7ChRi4Xr2AUt7okSutKNl2QI5cKTNWMYzfk8aP52ni5hUkgd+KEOOEqRBXyP/X4f5JyrJ+3PR3c0wg/32bWkJZqXqutfW0FGyYmBDZYF5vXlW5ICekIXtGIw+C35e2i/0D1qz4r7321ni5Cbf3sEqlhDKjPzUkUf20RavXFdNASC3UL53IODVqTy6wzSW6amMYSpqwU3shNiqdXaJGeGvfNiTfkAdeYnjA6gk+zrCPkv33jCdTRNdNnViknIXOJzqh0CDkVB9gpWXf+dc/LyRhDbQEWteQz9C1+blcGk/Wb7wS58SazIpS67T9EZFi/Tj4WhCDb7NqZyBMDzyzBeWfRUV133SpAHeVDqWta1kVzXsYGE7ir+dvkhtu9F4J4KHjNQH6W7FjgnWDY4P7QzkxNebuCDopiZbxWZtMkUJ4+U=
  app: lpa2khadidja
  on:
    repo: zahrijaa140/Projet
